#!/usr/bin/env python3
"""
Pulls artwork data (title, artist, date, medium, image) from the Studio
Museum in Harlem's public GraphQL API and writes it out as a JS file the
flashcard app can load directly (no server/build step required).

Usage:
    python3 fetch_data.py
"""

import json
import re
import time
import urllib.request
from pathlib import Path

API_URL = "https://admin.studiomuseum.org/api"
PAGE_SIZE = 100
REQUEST_DELAY_SECONDS = 0.3
OUTPUT_JS = Path(__file__).parent / "web" / "data.js"
OUTPUT_JSON = Path(__file__).parent / "data" / "artworks.json"

ARTWORK_FIELDS = """
    id
    slug
    title
    artworkNetxDate
    artworkNetxMedium
    artworkNetxDimensions
    artworkMedia {
        url
        width
        height
    }
    artworkType {
        title
    }
    artists: artworkArtist {
        ... on allArtists_allArtists_Entry {
            id
            slug
            title
            artistDates
        }
    }
"""


def graphql(query: str) -> dict:
    body = json.dumps({"query": query}).encode("utf-8")
    req = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "museum-flashcards-fetcher/1.0 (personal study app)",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = json.loads(resp.read())
    if "errors" in payload:
        raise RuntimeError(f"GraphQL errors: {payload['errors']}")
    return payload["data"]


def fetch_total_count() -> int:
    data = graphql('query { entryCount(type: "allArtworks") }')
    return data["entryCount"]


def fetch_page(limit: int, offset: int) -> list[dict]:
    query = f"""
    query {{
        entries(type: "allArtworks", limit: {limit}, offset: {offset}) {{
            ... on allArtworks_allArtworks_Entry {{
                {ARTWORK_FIELDS}
            }}
        }}
    }}
    """
    data = graphql(query)
    return data["entries"]


def decade_from_date(date_text: str | None) -> str | None:
    if not date_text:
        return None
    match = re.search(r"\d{4}", date_text)
    if not match:
        return None
    year = int(match.group())
    return f"{(year // 10) * 10}s"


def normalize(entry: dict) -> dict | None:
    media = entry.get("artworkMedia") or []
    artists = entry.get("artists") or []
    if not media or not media[0].get("url") or not artists:
        return None

    date = entry.get("artworkNetxDate") or "Date unknown"
    types = [t["title"] for t in (entry.get("artworkType") or []) if t.get("title")]

    return {
        "id": entry["id"],
        "slug": entry["slug"],
        "title": entry.get("title") or "Untitled",
        "artist": ", ".join(a["title"] for a in artists if a.get("title")),
        "artistDates": next((a.get("artistDates") for a in artists if a.get("artistDates")), None),
        "date": date,
        "decade": decade_from_date(date),
        "types": types,
        "medium": entry.get("artworkNetxMedium") or "Medium not recorded",
        "dimensions": entry.get("artworkNetxDimensions"),
        "image": media[0]["url"],
    }


def main() -> None:
    total = fetch_total_count()
    print(f"Studio Museum collection reports {total} artworks. Fetching...")

    raw_entries: list[dict] = []
    offset = 0
    while offset < total:
        page = fetch_page(PAGE_SIZE, offset)
        raw_entries.extend(page)
        offset += PAGE_SIZE
        print(f"  fetched {min(offset, total)}/{total}")
        time.sleep(REQUEST_DELAY_SECONDS)

    artworks = [a for a in (normalize(e) for e in raw_entries) if a is not None]
    skipped = len(raw_entries) - len(artworks)
    print(f"Kept {len(artworks)} artworks with usable image + artist data ({skipped} skipped).")

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(artworks, indent=2), encoding="utf-8")

    OUTPUT_JS.parent.mkdir(parents=True, exist_ok=True)
    js_content = "// Generated by fetch_data.py — do not edit by hand.\n"
    js_content += f"const ARTWORKS = {json.dumps(artworks)};\n"
    OUTPUT_JS.write_text(js_content, encoding="utf-8")

    print(f"Wrote {OUTPUT_JSON} and {OUTPUT_JS}")


if __name__ == "__main__":
    main()
